import { StyleSheet, Platform } from "react-native";

export const square = StyleSheet.create({
  button: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ccc",
    margin: 1,
    backgroundColor: "#f9fafb",
    borderRadius: 6,
    cursor: Platform.OS === 'web' ? 'pointer' : undefined,
  },
  buttonWinning: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ccc",
    margin: 1,
    backgroundColor: "#10b981",
    borderRadius: 6,
    cursor: Platform.OS === 'web' ? 'pointer' : undefined,
  },
  buttonDrawX: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ccc",
    margin: 1,
    backgroundColor: "#3b82f6",
    borderRadius: 6,
    cursor: Platform.OS === 'web' ? 'pointer' : undefined,
  },
  buttonDrawO: {
    justifyContent: "center",
    alignItems: "center",
    borderWidth: 2,
    borderColor: "#ccc",
    margin: 1,
    backgroundColor: "#ef4444",
    borderRadius: 6,
    cursor: Platform.OS === 'web' ? 'pointer' : undefined,
  },
  text: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#111827",
    userSelect: Platform.OS === 'web' ? 'none' : undefined,
  },
  textHighlighted: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#ffffff",
    userSelect: Platform.OS === 'web' ? 'none' : undefined,
  },
});